import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: {
  children: ReactNode
}) {
  return (
    <html lang='en'>
    <AppRouterCacheProvider>
      <body className={inter.className}>{children}</body>
    </AppRouterCacheProvider>
    </html>
  );
}
